import Foundation
import Combine

struct LyricsPosition: Equatable {
    let positionMs: Int
    let lineIndex: Int?
    let currentLine: String?
    let nextLine: String?

    /// 0–1 through the current line's time window.
    let lineProgress: Double

    /// 0–1 through the whole track.
    let trackProgress: Double

    let isPlaying: Bool
}

/// Keeps lyric timing aligned with the playback clock.
///
/// Instead of polling 10 times per second, the engine schedules one callback
/// for the exact timestamp of the next lyric line.
///
/// A lightweight 1-second progress timer remains so the in-app progress UI
/// still moves smoothly enough. Live Activity updates are not generated by
/// these progress ticks unless the lyric line actually changes.
final class SyncEngine {

    static let seekThresholdMs = 2000

    /// Only for progress/UI refreshes.
    /// Lyric changes themselves use the exact next-line scheduler below.
    static let progressTickInterval: TimeInterval = 1.0

    var now: () -> Date

    private(set) var anchor: NowPlayingState?
    private(set) var lines: [LRCLine] = []

    let positionSubject =
        CurrentValueSubject<LyricsPosition?, Never>(nil)

    private var progressTimer: AnyCancellable?

    /// Exact scheduled callback for the next lyric boundary.
    private var lineWorkItem: DispatchWorkItem?

    init(now: @escaping () -> Date = Date.init) {
        self.now = now
    }

    // MARK: - Lyrics

    func setLyrics(_ lines: [LRCLine]) {
        self.lines = lines

        tick()
        scheduleNextLineTransition()
    }

    // MARK: - Playback state

    /// Adopts a new source report.
    ///
    /// Small playback-position differences are treated as source polling
    /// jitter. Larger differences, track changes and play/pause changes
    /// replace the clock anchor and reschedule the next lyric boundary.
    func apply(_ state: NowPlayingState?) {

        guard let new = state else {
            anchor = nil
            cancelLineTransition()
            positionSubject.send(nil)
            return
        }

        var anchorChanged = true

        if let current = anchor,
           current.isSameTrack(as: new),
           current.isPlaying == new.isPlaying,
           new.isPlaying {

            let expected =
                Self.extrapolatedPositionMs(
                    anchor: current,
                    at: new.capturedAt
                )

            let thresholdMs: Int

            if new.source == .appleMusic {
                thresholdMs = 250
            } else {
                thresholdMs = Self.seekThresholdMs
            }

            if abs(expected - new.positionMs) <= thresholdMs {
                // Existing anchor is still accurate enough.
                anchorChanged = false
            }
        }

        if anchorChanged {
            anchor = new
        }

        tick()

        // Only rebuild the exact lyric timer when the playback clock really
        // changed, or when no line callback currently exists.
        if anchorChanged || lineWorkItem == nil {
            scheduleNextLineTransition()
        }
    }

    // MARK: - Running

    func startTicking() {
        guard progressTimer == nil else {
            scheduleNextLineTransition()
            return
        }

        progressTimer = Timer.publish(
            every: Self.progressTickInterval,
            on: .main,
            in: .common
        )
        .autoconnect()
        .sink { [weak self] _ in
            self?.tick()
        }

        tick()
        scheduleNextLineTransition()
    }

    func stopTicking() {
        progressTimer = nil
        cancelLineTransition()
    }

    // MARK: - Exact lyric scheduler

    private func scheduleNextLineTransition() {
        cancelLineTransition()

        guard let anchor,
              anchor.isPlaying,
              !lines.isEmpty else {
            return
        }

        let position =
            Self.extrapolatedPositionMs(
                anchor: anchor,
                at: now()
            )

        let targetTimeMs: Int

        if let currentIndex =
            Self.lineIndex(
                forPositionMs: position,
                in: lines
            ) {

            let nextIndex = currentIndex + 1

            guard nextIndex < lines.count else {
                return
            }

            targetTimeMs = lines[nextIndex].timeMs

        } else {

            // Playback is still before the first lyric line.
            targetTimeMs = lines[0].timeMs
        }

        let remainingMs = targetTimeMs - position

        // If we somehow passed the boundary already, immediately recalculate.
        guard remainingMs > 0 else {
            tick()

            DispatchQueue.main.async { [weak self] in
                self?.scheduleNextLineTransition()
            }

            return
        }

        let delay =
            TimeInterval(remainingMs) / 1000.0

        let workItem =
            DispatchWorkItem { [weak self] in

                guard let self else {
                    return
                }

                self.lineWorkItem = nil

                // Calculate against the playback clock again rather than
                // assuming the callback fired at the exact millisecond.
                self.tick()

                // Now schedule exactly the following lyric.
                self.scheduleNextLineTransition()
            }

        lineWorkItem = workItem

        DispatchQueue.main.asyncAfter(
            deadline: .now() + delay,
            execute: workItem
        )
    }

    private func cancelLineTransition() {
        lineWorkItem?.cancel()
        lineWorkItem = nil
    }

    // MARK: - Position emission

    func tick() {
        guard let anchor else {
            positionSubject.send(nil)
            return
        }

        let pos =
            Self.extrapolatedPositionMs(
                anchor: anchor,
                at: now()
            )

        positionSubject.send(
            Self.position(
                atMs: pos,
                lines: lines,
                durationMs: anchor.durationMs,
                isPlaying: anchor.isPlaying
            )
        )
    }

    // MARK: - Pure helpers

    static func extrapolatedPositionMs(
        anchor: NowPlayingState,
        at date: Date
    ) -> Int {

        guard anchor.isPlaying else {
            return anchor.positionMs
        }

        let elapsedMs =
            Int(
                (
                    date.timeIntervalSince(
                        anchor.capturedAt
                    ) * 1000
                ).rounded()
            )

        let pos =
            max(
                0,
                anchor.positionMs + elapsedMs
            )

        if let duration = anchor.durationMs {
            return min(pos, duration)
        }

        return pos
    }

    /// Index of the last lyric with timestamp <= current position.
    static func lineIndex(
        forPositionMs pos: Int,
        in lines: [LRCLine]
    ) -> Int? {

        guard let first = lines.first,
              pos >= first.timeMs else {
            return nil
        }

        var lo = 0
        var hi = lines.count - 1

        while lo < hi {

            let mid =
                (lo + hi + 1) / 2

            if lines[mid].timeMs <= pos {
                lo = mid
            } else {
                hi = mid - 1
            }
        }

        return lo
    }

    static func position(
        atMs pos: Int,
        lines: [LRCLine],
        durationMs: Int?,
        isPlaying: Bool
    ) -> LyricsPosition {

        let index =
            lineIndex(
                forPositionMs: pos,
                in: lines
            )

        let currentLine =
            index.map {
                lines[$0].text
            }

        let nextLine: String?

        if let index {

            nextLine =
                index + 1 < lines.count
                ? lines[index + 1].text
                : nil

        } else {

            nextLine =
                lines.first?.text
        }

        var lineProgress = 0.0

        if let index {

            let start =
                lines[index].timeMs

            let end =
                index + 1 < lines.count
                ? lines[index + 1].timeMs
                : (durationMs ?? start + 5000)

            if end > start {
                lineProgress =
                    min(
                        1,
                        max(
                            0,
                            Double(pos - start)
                                / Double(end - start)
                        )
                    )
            }
        }

        let trackProgress =
            durationMs.flatMap { duration in

                duration > 0
                ? min(
                    1,
                    max(
                        0,
                        Double(pos)
                            / Double(duration)
                    )
                )
                : nil

            } ?? 0

        return LyricsPosition(
            positionMs: pos,
            lineIndex: index,
            currentLine: currentLine,
            nextLine: nextLine,
            lineProgress: lineProgress,
            trackProgress: trackProgress,
            isPlaying: isPlaying
        )
    }
}